// Copyright (c) 2026 John Dewey

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package server

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"log/slog"
	"runtime/debug"
	"time"

	"github.com/danielgtaylor/huma/v2"
)

// requestIDKey is the context key under which the per-request id is
// stashed; pulled out by the request logger and (eventually) by
// handlers that want to surface it in error responses.
type requestIDKey struct{}

// RequestIDFromContext returns the per-request id when one was
// generated by the requestID middleware, or "" when called from
// outside the HTTP request lifecycle.
func RequestIDFromContext(ctx context.Context) string {
	if v, ok := ctx.Value(requestIDKey{}).(string); ok {
		return v
	}
	return ""
}

// registerMiddleware wires the global Huma middleware chain in
// outermost-first order: recovery (so a panic still gets logged),
// request-ID (so the logger has it), then the request log itself.
// New middleware (auth, rate limit, audit) gets appended here.
func (s *Server) registerMiddleware() {
	s.api.UseMiddleware(s.recoveryMiddleware)
	s.api.UseMiddleware(s.requestIDMiddleware)
	s.api.UseMiddleware(s.requestLogMiddleware)
}

// requestIDMiddleware honors an inbound X-Request-ID when the client
// supplies one (so traces stitch through a reverse proxy), otherwise
// generates a fresh 8-byte hex id. The id is echoed in the response
// header and stashed on the request context for the logger.
func (s *Server) requestIDMiddleware(ctx huma.Context, next func(huma.Context)) {
	id := ctx.Header("X-Request-ID")
	if id == "" {
		id = newRequestID()
	}
	ctx.SetHeader("X-Request-ID", id)
	ctx = huma.WithValue(ctx, requestIDKey{}, id)
	next(ctx)
}

// requestLogMiddleware emits one structured line per request after
// the handler returns: method, path, status, duration, request_id,
// remote, user-agent. Errors (5xx) escalate to Error, 4xx to Warn,
// rest Info — so a debug-level filter stays useful in production.
func (s *Server) requestLogMiddleware(ctx huma.Context, next func(huma.Context)) {
	start := time.Now()
	next(ctx)

	status := ctx.Status()
	url := ctx.URL()
	level := slog.LevelInfo
	switch {
	case status >= 500:
		level = slog.LevelError
	case status >= 400:
		level = slog.LevelWarn
	}

	s.logger.LogAttrs(ctx.Context(), level, "request",
		slog.String("method", ctx.Method()),
		slog.String("path", url.Path),
		slog.Int("status", status),
		slog.Duration("duration", time.Since(start)),
		slog.String("request_id", RequestIDFromContext(ctx.Context())),
		slog.String("remote", ctx.RemoteAddr()),
		slog.String("user_agent", ctx.Header("User-Agent")),
	)
}

// recoveryMiddleware catches panics in handlers, logs them with the
// stack trace, and returns a 500. Without this a panic crashes the
// goroutine but http.Server keeps running with the connection in a
// broken state — better to surface a real status.
func (s *Server) recoveryMiddleware(ctx huma.Context, next func(huma.Context)) {
	defer func() {
		if r := recover(); r != nil {
			s.logger.LogAttrs(ctx.Context(), slog.LevelError, "panic recovered",
				slog.Any("panic", r),
				slog.String("stack", string(debug.Stack())),
				slog.String("method", ctx.Method()),
				slog.String("path", ctx.URL().Path),
				slog.String("request_id", RequestIDFromContext(ctx.Context())),
			)
			err := huma.Error500InternalServerError("internal server error")
			_ = huma.WriteErr(s.api, ctx, 500, err.Error())
		}
	}()
	next(ctx)
}

// newRequestID returns 8 hex bytes (16 chars) of randomness — short
// enough to fit a header and a log line without being noisy, long
// enough that collisions inside a single deployment are vanishingly
// unlikely.
func newRequestID() string {
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		// crypto/rand.Read on darwin/linux only fails when the kernel
		// PRNG is uninitialized, which doesn't happen post-boot. Fall
		// back to a fixed sentinel rather than panic.
		return "0000000000000000"
	}
	return hex.EncodeToString(b[:])
}
