// Code generated by mcpgen; DO NOT EDIT.

package mcp

import (
	"context"
	"fmt"

	mcpsdk "github.com/modelcontextprotocol/go-sdk/mcp"
	gen "github.com/retr0h/meshx/internal/sdk/gen"
)

// registerGeneratedTools wires every spec-derived MCP tool onto s.mcp.
// Called from registerTools() in tools.go.
func (s *Server) registerGeneratedTools() {
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Dial a radio transport (ble:<uuid>, /dev/cu.usb…, host:port) and register it in the daemon's registry without restarting. The pump connects, runs the Meshtastic handshake, and the radio appears in GET /radios once MyInfo arrives. Returns the pending radio_id immediately.",
		Name:        "attach_radio",
	}, s.toolAttachRadio)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Convenience over /transports/usb/scan — returns the device path of the single Meshtastic radio found. 404 when zero, 409 when multiple.",
		Name:        "auto_detect_usb",
	}, s.toolAutoDetectUsb)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Removes the favorite flag from whichever device currently holds it. Auto-connect falls back to the single-saved-device rule.",
		Name:        "clear_ble_favorite",
	}, s.toolClearBleFavorite)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Dispatches DeleteChannel to free the named slot — radio sets the slot's role to DISABLED and wipes the PSK. Refuses slot 0 (PRIMARY) since the firmware requires one to operate. Returns 202 Accepted; the radio's confirmation arrives later as the matching channel event on the SSE stream.",
		Name:        "delete_channel",
	}, s.toolDeleteChannel)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Tear down the pump + transport and remove the radio from the registry. The radio stops responding to mesh traffic; the daemon stays up. Idempotent — detaching an unknown radio_id returns 404.",
		Name:        "detach_radio",
	}, s.toolDetachRadio)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Removes the device from the saved-pairings table. Does not unbind at the OS level.",
		Name:        "forget_ble_device",
	}, s.toolForgetBleDevice)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Identity, telemetry, current channel, connection status for one radio. Useful for clients rendering a status bar.",
		Name:        "get_radio",
	}, s.toolGetRadio)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Cheap probe for orchestration (systemd, k8s, docker healthcheck). Touches no state.",
		Name:        "health",
	}, s.toolHealth)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Parses a meshtastic:// (or https://meshtastic.org/e/) share URL and dispatches SetChannel for each channel inside that fits a free slot. Multi-channel URLs are handled per-slot — collisions and full-slot-table conditions are recorded in skipped[] rather than failing the whole call. Returns 202 Accepted with imported / skipped lists.",
		Name:        "import_channels",
	}, s.toolImportChannels)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns every BLE device the daemon has saved for auto-connect. Favorite devices are flagged.",
		Name:        "list_ble_devices",
	}, s.toolListBleDevices)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns the radio's channel table — name, role, slot index, has-PSK flag. PSK bytes are NEVER emitted by this endpoint; they stay on the daemon side.",
		Name:        "list_channels",
	}, s.toolListChannels)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns persisted + live in-memory chat rows in chronological order. Optional ?limit= caps response to the most recent N rows.",
		Name:        "list_messages",
	}, s.toolListMessages)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns every peer the radio's NodeDB has seen, with the most-recent telemetry (SNR, RSSI, hops) and derived state (online / offline / muted).",
		Name:        "list_nodes",
	}, s.toolListNodes)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns every radio currently registered with the daemon — radio_id, identity, connection status. Clients use this to populate a radio picker before drilling into per-radio resources.",
		Name:        "list_radios",
	}, s.toolListRadios)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Generates a 32-byte AES256 PSK and a random Channel.id, dispatches SetChannel into the first free secondary slot (1..7), and returns the meshtastic:// share URL so the caller can hand it off in person (QR rendering is a client concern). Raw PSK bytes never cross the wire — clients receive only the URL. Returns 202 Accepted; the radio's confirmation arrives later as the matching channel event on the SSE stream.",
		Name:        "mint_channel",
	}, s.toolMintChannel)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Opens an encrypted GATT connection to trigger OS-level bonding (PIN prompt on macOS, agent on Linux), then saves the device to the daemon's pairing table.",
		Name:        "pair_ble",
	}, s.toolPairBle)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Dispatches a Meshtastic REPLY_APP ping to the named peer. The radio echoes the packet back, which the daemon surfaces as a `ping` SSE event correlated by `packet_id`. Returns 202 Accepted with the allocated `packet_id`. Fire-and-forget at the HTTP layer; clients consume `/radios/{id}/events` to observe the round-trip.",
		Name:        "ping_peer",
	}, s.toolPingPeer)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Schedules a firmware reboot N seconds out (default 5 to mirror the TUI's /reboot grace). The radio drops carrier during reboot — clients should expect the SSE stream to disconnect and the daemon to auto-reconnect once the radio comes back. Returns 202 Accepted with the acknowledged delay.",
		Name:        "reboot_radio",
	}, s.toolRebootRadio)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Runs a discovery scan for the configured timeout (default 10s) and returns peripherals advertising the Meshtastic GATT service.",
		Name:        "scan_ble",
	}, s.toolScanBle)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Walks every candidate USB-serial port, sends a Meshtastic WantConfigId handshake, returns each port's outcome (IsMeshtastic + node identity, or a reason it didn't respond).",
		Name:        "scan_usb",
	}, s.toolScanUsb)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Enqueues an outbound text message on the named channel. Returns the allocated MeshPacket.id; clients correlate this with subsequent ack / fail events from the SSE stream. Pass an `Idempotency-Key` header (typically a UUID) for retry dedupe — identical key on the same radio within 60s returns the original result without dispatching to the radio a second time. Without the header, every request hits the radio (legacy behavior).",
		Name:        "send_message",
	}, s.toolSendMessage)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Sets this device as the bare-`meshx` auto-connect target when no USB radio is plugged in.",
		Name:        "set_ble_favorite",
	}, s.toolSetBleFavorite)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Builds a meshtastic:// universal-link share URL for the named channel slot, carrying name + PSK + id. Useful for clients that want to render their own QR for in-person handoff.",
		Name:        "share_channel",
	}, s.toolShareChannel)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Fires a WantConfigId at the radio so it re-dumps its NodeDB, channel table, configs (LoRa / device / position), Metadata, and ConfigComplete. Each arrives as its own SSE event over the next few seconds. Useful when a remote client suspects its cached state has drifted (e.g., after a long reconnect gap) and wants the radio to retransmit ground truth. Returns 202 Accepted; no correlator on the wire — every SSE event during the dump is independent.",
		Name:        "sync_radio",
	}, s.toolSyncRadio)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Dispatches a Meshtastic TRACEROUTE_APP RouteDiscovery request to the named peer. The radio walks the mesh and echoes a TRACEROUTE_APP reply back, which the daemon surfaces as a `traceroute` SSE event carrying the ordered list of intermediate nodes the discovery walked through. Returns 202 Accepted with the allocated `packet_id` for SSE correlation.",
		Name:        "traceroute_peer",
	}, s.toolTraceroutePeer)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Partial-update for the radio's User record (longname / shortname / is_licensed) and ExternalNotification buzzer. Body fields are optional; omitted keys are left untouched. Dispatched fire-and-forget — confirmation arrives later as the matching Apply* event on the SSE stream. Returns 202 Accepted; the Applied array names exactly which fields were forwarded to the radio.",
		Name:        "update_config",
	}, s.toolUpdateConfig)
}

type attachRadioArgs struct {
	Dest string `json:"dest" jsonschema:"transport target: /dev/cu.usb…, ble:<uuid>, host:port"`
}

func (s *Server) toolAttachRadio(ctx context.Context, _ *mcpsdk.CallToolRequest, args attachRadioArgs) (*mcpsdk.CallToolResult, any, error) {
	body := gen.AttachRadioJSONRequestBody{}
	body.Dest = args.Dest
	resp, err := s.client.AttachRadioWithResponse(ctx, body)
	if err != nil {
		return nil, nil, fmt.Errorf("attach_radio: %w", err)
	}
	if resp.JSON200 == nil {
		return nil, nil, fmt.Errorf("attach_radio: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON200)), nil, nil
}

type autoDetectUsbArgs struct {
	TimeoutMs int64 `json:"timeout_ms,omitempty" jsonschema:"per-port identify timeout in milliseconds; default 1500"`
}

func (s *Server) toolAutoDetectUsb(ctx context.Context, _ *mcpsdk.CallToolRequest, args autoDetectUsbArgs) (*mcpsdk.CallToolResult, any, error) {
	body := gen.AutoDetectUsbJSONRequestBody{}
	if args.TimeoutMs != 0 {
		v := int64(args.TimeoutMs)
		body.TimeoutMs = &v
	}
	resp, err := s.client.AutoDetectUsbWithResponse(ctx, body)
	if err != nil {
		return nil, nil, fmt.Errorf("auto_detect_usb: %w", err)
	}
	if resp.JSON200 == nil {
		return nil, nil, fmt.Errorf("auto_detect_usb: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON200)), nil, nil
}

func (s *Server) toolClearBleFavorite(ctx context.Context, _ *mcpsdk.CallToolRequest, args struct{}) (*mcpsdk.CallToolResult, any, error) {
	resp, err := s.client.ClearBleFavoriteWithResponse(ctx)
	if err != nil {
		return nil, nil, fmt.Errorf("clear_ble_favorite: %w", err)
	}
	if resp.StatusCode() < 200 || resp.StatusCode() >= 300 {
		return nil, nil, fmt.Errorf("clear_ble_favorite: daemon returned %s", resp.Status())
	}
	return textResult(fmt.Sprintf("clear_ble_favorite: ok (%s)", resp.Status())), nil, nil
}

type deleteChannelArgs struct {
	RadioId string `json:"radio_id" jsonschema:"canonical radio identifier — see GET /radios"`
	Index   int64  `json:"index" jsonschema:"slot index 1..7 (slot 0 is PRIMARY and cannot be deleted)"`
}

func (s *Server) toolDeleteChannel(ctx context.Context, _ *mcpsdk.CallToolRequest, args deleteChannelArgs) (*mcpsdk.CallToolResult, any, error) {
	resp, err := s.client.DeleteChannelWithResponse(ctx, args.RadioId, int64(args.Index))
	if err != nil {
		return nil, nil, fmt.Errorf("delete_channel: %w", err)
	}
	if resp.StatusCode() < 200 || resp.StatusCode() >= 300 {
		return nil, nil, fmt.Errorf("delete_channel: daemon returned %s", resp.Status())
	}
	return textResult(fmt.Sprintf("delete_channel: ok (%s)", resp.Status())), nil, nil
}

type detachRadioArgs struct {
	RadioId string `json:"radio_id" jsonschema:"canonical radio identifier — see GET /radios"`
}

func (s *Server) toolDetachRadio(ctx context.Context, _ *mcpsdk.CallToolRequest, args detachRadioArgs) (*mcpsdk.CallToolResult, any, error) {
	resp, err := s.client.DetachRadioWithResponse(ctx, args.RadioId)
	if err != nil {
		return nil, nil, fmt.Errorf("detach_radio: %w", err)
	}
	if resp.StatusCode() < 200 || resp.StatusCode() >= 300 {
		return nil, nil, fmt.Errorf("detach_radio: daemon returned %s", resp.Status())
	}
	return textResult(fmt.Sprintf("detach_radio: ok (%s)", resp.Status())), nil, nil
}

type forgetBleDeviceArgs struct {
	Uuid string `json:"uuid" jsonschema:"peripheral identifier or saved long/short name"`
}

func (s *Server) toolForgetBleDevice(ctx context.Context, _ *mcpsdk.CallToolRequest, args forgetBleDeviceArgs) (*mcpsdk.CallToolResult, any, error) {
	resp, err := s.client.ForgetBleDeviceWithResponse(ctx, args.Uuid)
	if err != nil {
		return nil, nil, fmt.Errorf("forget_ble_device: %w", err)
	}
	if resp.StatusCode() < 200 || resp.StatusCode() >= 300 {
		return nil, nil, fmt.Errorf("forget_ble_device: daemon returned %s", resp.Status())
	}
	return textResult(fmt.Sprintf("forget_ble_device: ok (%s)", resp.Status())), nil, nil
}

type getRadioArgs struct {
	RadioId string `json:"radio_id" jsonschema:"canonical radio identifier — see GET /radios"`
}

func (s *Server) toolGetRadio(ctx context.Context, _ *mcpsdk.CallToolRequest, args getRadioArgs) (*mcpsdk.CallToolResult, any, error) {
	resp, err := s.client.GetRadioWithResponse(ctx, args.RadioId)
	if err != nil {
		return nil, nil, fmt.Errorf("get_radio: %w", err)
	}
	if resp.JSON200 == nil {
		return nil, nil, fmt.Errorf("get_radio: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON200)), nil, nil
}

func (s *Server) toolHealth(ctx context.Context, _ *mcpsdk.CallToolRequest, args struct{}) (*mcpsdk.CallToolResult, any, error) {
	resp, err := s.client.HealthWithResponse(ctx)
	if err != nil {
		return nil, nil, fmt.Errorf("health: %w", err)
	}
	if resp.JSON200 == nil {
		return nil, nil, fmt.Errorf("health: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON200)), nil, nil
}

type importChannelsArgs struct {
	RadioId string `json:"radio_id" jsonschema:"canonical radio identifier — see GET /radios"`
	Url     string `json:"url" jsonschema:"meshtastic:// or https://meshtastic.org/e/ share URL"`
}

func (s *Server) toolImportChannels(ctx context.Context, _ *mcpsdk.CallToolRequest, args importChannelsArgs) (*mcpsdk.CallToolResult, any, error) {
	body := gen.ImportChannelsJSONRequestBody{}
	body.Url = args.Url
	resp, err := s.client.ImportChannelsWithResponse(ctx, args.RadioId, body)
	if err != nil {
		return nil, nil, fmt.Errorf("import_channels: %w", err)
	}
	if resp.JSON202 == nil {
		return nil, nil, fmt.Errorf("import_channels: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON202)), nil, nil
}

func (s *Server) toolListBleDevices(ctx context.Context, _ *mcpsdk.CallToolRequest, args struct{}) (*mcpsdk.CallToolResult, any, error) {
	resp, err := s.client.ListBleDevicesWithResponse(ctx)
	if err != nil {
		return nil, nil, fmt.Errorf("list_ble_devices: %w", err)
	}
	if resp.JSON200 == nil {
		return nil, nil, fmt.Errorf("list_ble_devices: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON200)), nil, nil
}

type listChannelsArgs struct {
	RadioId string `json:"radio_id" jsonschema:"canonical radio identifier — see GET /radios"`
}

func (s *Server) toolListChannels(ctx context.Context, _ *mcpsdk.CallToolRequest, args listChannelsArgs) (*mcpsdk.CallToolResult, any, error) {
	resp, err := s.client.ListChannelsWithResponse(ctx, args.RadioId)
	if err != nil {
		return nil, nil, fmt.Errorf("list_channels: %w", err)
	}
	if resp.JSON200 == nil {
		return nil, nil, fmt.Errorf("list_channels: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON200)), nil, nil
}

type listMessagesArgs struct {
	RadioId string `json:"radio_id" jsonschema:"canonical radio identifier — see GET /radios"`
	Limit   int64  `json:"limit,omitempty" jsonschema:"max rows to return; 0 = no limit"`
	Dm      string `json:"dm,omitempty" jsonschema:"DM filter; '' = all rows, '1' = peer-addressed DMs (either direction), 'mine' = DMs to/from my_node_num. Use to skip channel-firehose filtering on the client side"`
}

func (s *Server) toolListMessages(ctx context.Context, _ *mcpsdk.CallToolRequest, args listMessagesArgs) (*mcpsdk.CallToolResult, any, error) {
	var params *gen.ListMessagesParams
	if args.Limit != 0 {
		if params == nil {
			params = &gen.ListMessagesParams{}
		}
		v := int64(args.Limit)
		params.Limit = &v
	}
	if args.Dm != "" {
		if params == nil {
			params = &gen.ListMessagesParams{}
		}
		v := gen.ListMessagesParamsDm(args.Dm)
		params.Dm = &v
	}
	resp, err := s.client.ListMessagesWithResponse(ctx, args.RadioId, params)
	if err != nil {
		return nil, nil, fmt.Errorf("list_messages: %w", err)
	}
	if resp.JSON200 == nil {
		return nil, nil, fmt.Errorf("list_messages: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON200)), nil, nil
}

type listNodesArgs struct {
	RadioId string `json:"radio_id" jsonschema:"canonical radio identifier — see GET /radios"`
}

func (s *Server) toolListNodes(ctx context.Context, _ *mcpsdk.CallToolRequest, args listNodesArgs) (*mcpsdk.CallToolResult, any, error) {
	resp, err := s.client.ListNodesWithResponse(ctx, args.RadioId)
	if err != nil {
		return nil, nil, fmt.Errorf("list_nodes: %w", err)
	}
	if resp.JSON200 == nil {
		return nil, nil, fmt.Errorf("list_nodes: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON200)), nil, nil
}

func (s *Server) toolListRadios(ctx context.Context, _ *mcpsdk.CallToolRequest, args struct{}) (*mcpsdk.CallToolResult, any, error) {
	resp, err := s.client.ListRadiosWithResponse(ctx)
	if err != nil {
		return nil, nil, fmt.Errorf("list_radios: %w", err)
	}
	if resp.JSON200 == nil {
		return nil, nil, fmt.Errorf("list_radios: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON200)), nil, nil
}

type mintChannelArgs struct {
	RadioId string `json:"radio_id" jsonschema:"canonical radio identifier — see GET /radios"`
	Name    string `json:"name" jsonschema:"channel name (1..11 bytes UTF-8); Meshtastic packs this into the share URL"`
}

func (s *Server) toolMintChannel(ctx context.Context, _ *mcpsdk.CallToolRequest, args mintChannelArgs) (*mcpsdk.CallToolResult, any, error) {
	body := gen.MintChannelJSONRequestBody{}
	body.Name = args.Name
	resp, err := s.client.MintChannelWithResponse(ctx, args.RadioId, body)
	if err != nil {
		return nil, nil, fmt.Errorf("mint_channel: %w", err)
	}
	if resp.JSON202 == nil {
		return nil, nil, fmt.Errorf("mint_channel: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON202)), nil, nil
}

type pairBleArgs struct {
	Uuid string `json:"uuid" jsonschema:"peripheral identifier from a /transports/ble/scan result"`
}

func (s *Server) toolPairBle(ctx context.Context, _ *mcpsdk.CallToolRequest, args pairBleArgs) (*mcpsdk.CallToolResult, any, error) {
	body := gen.PairBleJSONRequestBody{}
	body.Uuid = args.Uuid
	resp, err := s.client.PairBleWithResponse(ctx, body)
	if err != nil {
		return nil, nil, fmt.Errorf("pair_ble: %w", err)
	}
	if resp.JSON200 == nil {
		return nil, nil, fmt.Errorf("pair_ble: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON200)), nil, nil
}

type pingPeerArgs struct {
	RadioId string `json:"radio_id" jsonschema:"canonical radio identifier — see GET /radios"`
	ToNum   int64  `json:"to_num" jsonschema:"peer NodeNum to ping; the firmware echoes a REPLY_APP packet back which lands as a 'ping' SSE event correlated by the returned packet_id"`
}

func (s *Server) toolPingPeer(ctx context.Context, _ *mcpsdk.CallToolRequest, args pingPeerArgs) (*mcpsdk.CallToolResult, any, error) {
	body := gen.PingPeerJSONRequestBody{}
	body.ToNum = args.ToNum
	resp, err := s.client.PingPeerWithResponse(ctx, args.RadioId, body)
	if err != nil {
		return nil, nil, fmt.Errorf("ping_peer: %w", err)
	}
	if resp.JSON202 == nil {
		return nil, nil, fmt.Errorf("ping_peer: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON202)), nil, nil
}

type rebootRadioArgs struct {
	RadioId string `json:"radio_id" jsonschema:"canonical radio identifier — see GET /radios"`
	Seconds int32  `json:"seconds,omitempty" jsonschema:"delay before reboot in seconds; 0 = now (default 5 matches the TUI's /reboot grace)"`
}

func (s *Server) toolRebootRadio(ctx context.Context, _ *mcpsdk.CallToolRequest, args rebootRadioArgs) (*mcpsdk.CallToolResult, any, error) {
	body := gen.RebootRadioJSONRequestBody{}
	if args.Seconds != 0 {
		v := int32(args.Seconds)
		body.Seconds = &v
	}
	resp, err := s.client.RebootRadioWithResponse(ctx, args.RadioId, body)
	if err != nil {
		return nil, nil, fmt.Errorf("reboot_radio: %w", err)
	}
	if resp.JSON202 == nil {
		return nil, nil, fmt.Errorf("reboot_radio: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON202)), nil, nil
}

type scanBleArgs struct {
	TimeoutMs int64 `json:"timeout_ms,omitempty" jsonschema:"scan duration in milliseconds; default 10000"`
}

func (s *Server) toolScanBle(ctx context.Context, _ *mcpsdk.CallToolRequest, args scanBleArgs) (*mcpsdk.CallToolResult, any, error) {
	body := gen.ScanBleJSONRequestBody{}
	if args.TimeoutMs != 0 {
		v := int64(args.TimeoutMs)
		body.TimeoutMs = &v
	}
	resp, err := s.client.ScanBleWithResponse(ctx, body)
	if err != nil {
		return nil, nil, fmt.Errorf("scan_ble: %w", err)
	}
	if resp.JSON200 == nil {
		return nil, nil, fmt.Errorf("scan_ble: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON200)), nil, nil
}

type scanUsbArgs struct {
	TimeoutMs int64 `json:"timeout_ms,omitempty" jsonschema:"per-port identify timeout in milliseconds; default 1500"`
}

func (s *Server) toolScanUsb(ctx context.Context, _ *mcpsdk.CallToolRequest, args scanUsbArgs) (*mcpsdk.CallToolResult, any, error) {
	body := gen.ScanUsbJSONRequestBody{}
	if args.TimeoutMs != 0 {
		v := int64(args.TimeoutMs)
		body.TimeoutMs = &v
	}
	resp, err := s.client.ScanUsbWithResponse(ctx, body)
	if err != nil {
		return nil, nil, fmt.Errorf("scan_usb: %w", err)
	}
	if resp.JSON200 == nil {
		return nil, nil, fmt.Errorf("scan_usb: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON200)), nil, nil
}

type sendMessageArgs struct {
	RadioId        string `json:"radio_id" jsonschema:"canonical radio identifier — see GET /radios"`
	IdempotencyKey string `json:"idempotency_key,omitempty" jsonschema:"opaque request key (typically a UUID) for retry dedupe; identical key on the same radio within 60s returns the original result without re-dispatching to the radio"`
	Channel        int64  `json:"channel" jsonschema:"target channel slot index (0..7); the current channel's slot is the default"`
	ReplyId        int64  `json:"reply_id,omitempty" jsonschema:"PacketID this message replies to"`
	Text           string `json:"text" jsonschema:"message body"`
	ToNum          int64  `json:"to_num,omitempty" jsonschema:"recipient NodeNum for a DM (peer-addressed unicast); 0 = broadcast on the channel. Look up the numeric NodeNum via GET /radios/{radio_id}/nodes — callsigns are not resolved server-side."`
}

func (s *Server) toolSendMessage(ctx context.Context, _ *mcpsdk.CallToolRequest, args sendMessageArgs) (*mcpsdk.CallToolResult, any, error) {
	var params *gen.SendMessageParams
	if args.IdempotencyKey != "" {
		if params == nil {
			params = &gen.SendMessageParams{}
		}
		v := args.IdempotencyKey
		params.IdempotencyKey = &v
	}
	body := gen.SendMessageJSONRequestBody{}
	body.Channel = args.Channel
	if args.ReplyId != 0 {
		v := int64(args.ReplyId)
		body.ReplyId = &v
	}
	body.Text = args.Text
	if args.ToNum != 0 {
		v := int64(args.ToNum)
		body.ToNum = &v
	}
	resp, err := s.client.SendMessageWithResponse(ctx, args.RadioId, params, body)
	if err != nil {
		return nil, nil, fmt.Errorf("send_message: %w", err)
	}
	if resp.JSON200 == nil {
		return nil, nil, fmt.Errorf("send_message: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON200)), nil, nil
}

type setBleFavoriteArgs struct {
	Uuid string `json:"uuid" jsonschema:"peripheral identifier or saved long/short name"`
}

func (s *Server) toolSetBleFavorite(ctx context.Context, _ *mcpsdk.CallToolRequest, args setBleFavoriteArgs) (*mcpsdk.CallToolResult, any, error) {
	resp, err := s.client.SetBleFavoriteWithResponse(ctx, args.Uuid)
	if err != nil {
		return nil, nil, fmt.Errorf("set_ble_favorite: %w", err)
	}
	if resp.JSON200 == nil {
		return nil, nil, fmt.Errorf("set_ble_favorite: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON200)), nil, nil
}

type shareChannelArgs struct {
	RadioId string `json:"radio_id" jsonschema:"canonical radio identifier — see GET /radios"`
	Index   int64  `json:"index" jsonschema:"slot index 0..7"`
}

func (s *Server) toolShareChannel(ctx context.Context, _ *mcpsdk.CallToolRequest, args shareChannelArgs) (*mcpsdk.CallToolResult, any, error) {
	resp, err := s.client.ShareChannelWithResponse(ctx, args.RadioId, int64(args.Index))
	if err != nil {
		return nil, nil, fmt.Errorf("share_channel: %w", err)
	}
	if resp.JSON200 == nil {
		return nil, nil, fmt.Errorf("share_channel: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON200)), nil, nil
}

type syncRadioArgs struct {
	RadioId string `json:"radio_id" jsonschema:"canonical radio identifier — see GET /radios"`
}

func (s *Server) toolSyncRadio(ctx context.Context, _ *mcpsdk.CallToolRequest, args syncRadioArgs) (*mcpsdk.CallToolResult, any, error) {
	resp, err := s.client.SyncRadioWithResponse(ctx, args.RadioId)
	if err != nil {
		return nil, nil, fmt.Errorf("sync_radio: %w", err)
	}
	if resp.JSON202 == nil {
		return nil, nil, fmt.Errorf("sync_radio: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON202)), nil, nil
}

type traceroutePeerArgs struct {
	RadioId string `json:"radio_id" jsonschema:"canonical radio identifier — see GET /radios"`
	ToNum   int64  `json:"to_num" jsonschema:"peer NodeNum to trace a route to; the firmware walks the mesh and echoes a TRACEROUTE_APP packet back which lands as a 'traceroute' SSE event correlated by the returned packet_id"`
}

func (s *Server) toolTraceroutePeer(ctx context.Context, _ *mcpsdk.CallToolRequest, args traceroutePeerArgs) (*mcpsdk.CallToolResult, any, error) {
	body := gen.TraceroutePeerJSONRequestBody{}
	body.ToNum = args.ToNum
	resp, err := s.client.TraceroutePeerWithResponse(ctx, args.RadioId, body)
	if err != nil {
		return nil, nil, fmt.Errorf("traceroute_peer: %w", err)
	}
	if resp.JSON202 == nil {
		return nil, nil, fmt.Errorf("traceroute_peer: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON202)), nil, nil
}

type updateConfigArgs struct {
	RadioId    string `json:"radio_id" jsonschema:"canonical radio identifier — see GET /radios"`
	Buzzer     *bool  `json:"buzzer,omitempty" jsonschema:"toggle the radio's external-notification buzzer (true = on, false = off)"`
	IsLicensed *bool  `json:"is_licensed,omitempty" jsonschema:"FCC-licensed flag on the User record; preserved when omitted"`
	Longname   string `json:"longname,omitempty" jsonschema:"radio operator longname (1..36 bytes UTF-8)"`
	Shortname  string `json:"shortname,omitempty" jsonschema:"radio operator shortname (1..4 bytes UTF-8 — emoji counts as its byte length)"`
}

func (s *Server) toolUpdateConfig(ctx context.Context, _ *mcpsdk.CallToolRequest, args updateConfigArgs) (*mcpsdk.CallToolResult, any, error) {
	body := gen.UpdateConfigJSONRequestBody{}
	if args.Buzzer != nil {
		body.Buzzer = args.Buzzer
	}
	if args.IsLicensed != nil {
		body.IsLicensed = args.IsLicensed
	}
	if args.Longname != "" {
		v := args.Longname
		body.Longname = &v
	}
	if args.Shortname != "" {
		v := args.Shortname
		body.Shortname = &v
	}
	resp, err := s.client.UpdateConfigWithResponse(ctx, args.RadioId, body)
	if err != nil {
		return nil, nil, fmt.Errorf("update_config: %w", err)
	}
	if resp.JSON202 == nil {
		return nil, nil, fmt.Errorf("update_config: daemon returned %s", resp.Status())
	}
	return textResult(jsonOrErr(resp.JSON202)), nil, nil
}
